apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-artifacts
  labels:
    {{- include "nereid.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-artifacts
  template:
    metadata:
      annotations:
        checksum/config-artifacts-nginx: {{ include (print $.Template.BasePath "/configmap-artifacts-nginx.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-artifacts
        {{- include "nereid.labels" . | nindent 8 }}
    spec:
      containers:
        - name: artifacts
          image: {{ .Values.images.artifacts }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: artifacts
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-artifacts-nginx
        - name: artifacts
          hostPath:
            path: {{ .Values.artifacts.hostPath }}
            type: Directory
